# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: 580373278c5a8703ebc228b886c7866641b2f147871122a0e3dd83b2e367fd14753cb62d4d003bde82f95b56ea9030eb60066eebd947efb55e85756ca01cb937

test:
  secret_key_base: c495f1968d682f73347206a91e996c78c393d1c9a16a1f411237e4cccd5ab30b8c90751a87d9407a4e6f1e130ec7329115dce9c602d22f07dae0d075eab16dbb

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
